server:
  servlet:
    context-path: /point-grabber
  port: 8888

logging:
  level:
    root: info

account:
  baidu:
    username: ''
    password: ''
  netease:
    username: ''
    password: ''


webdriver:
  chrome:
    path: 'G:/point-grabber/drivers/win-chrome-79.0.3945.16/chromedriver.exe'